// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMFG.MinhaPrimeira.API.Repositorio.Context;

#nullable disable

namespace UMFG.MinhaPrimeira.API.Repositorio.Migrations
{
    [DbContext(typeof(MySqlDatabaseContext))]
    [Migration("20240322225655_MigrationUnificada_1_0_0_0")]
    partial class MigrationUnificada_1_0_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UMFG.MinhaPrimeira.API.Dominio.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_ALTERACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_PRODUTO");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CD_EAN");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_CUSTO");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_VENDA");

                    b.Property<string>("UsuarioAlteracao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_USUARIO_ALTERACAO");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_USUARIO_CADASTRO");

                    b.HasKey("Id");

                    b.ToTable("PRODUTO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
